name: main

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run ShellCheck
        run: shellcheck bin/*
        
  plugin_test:
    needs: [lint]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ver:  [0.14.0, 0.15.2]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2.1.0
        with:
          version: ${{ matrix.ver }}
          command: restic version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}